#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model HPF.Test.FFT_mag_phase_reconstruct
 Dymola Version 2020 (64-bit), 2019-04-10 translated this at Tue Oct 15 14:01:50 2019

  Evaluate = true;
 */

#include <matrixop.h>
static double DymArrays0[166]={0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
   0.0};
/* Declaration of C-structs */
/* Prototypes for functions used in model */
struct HPF_Utilities_fftx_0fromMagPhase_struct {
  RealArray    yRe0_0_0member;
  RealArray    yIm0_0_0member;
};
DYMOLA_STATIC struct HPF_Utilities_fftx_0fromMagPhase_struct HPF_Utilities_fftx_0fromMagPhase
  (RealArray   mag0_0, RealArray   arg0_0, int  N0_0);
DYMOLA_STATIC RealArray    Modelica_Utilities_Streams_readRealMatrix_M(
  const char*  fileName0_0, const char*  matrixName0_0, int  nrow0_0, int  
  ncol0_0, int  verboseRead0_0);
DYMOLA_STATIC RealArray    cos_For_1_0(RealArray   u0_0);
DYMOLA_STATIC RealArray    multScalar_For_1_0(RealArray   x_0x1, double  x_0x2);
DYMOLA_STATIC RealArray    multScalar_For_1_0_1(RealArray   x_0x1, RealArray   
  x_0x2);
DYMOLA_STATIC RealArray    sin_For_1_0(RealArray   u0_0);
DYMOLA_STATIC RealArray    subScalar_For_1_0(RealArray   x_0x1, double  x_0x2);
/* Codes used in model */

/* Flattened Modelica model:

function HPF.Utilities.fft_fromMagPhase
discrete input Real mag[:] "Magnitude data of the harmonics";
discrete input Real arg[:] "Phase data of the harmonics";
input Integer N "Size of the FFT";
discrete output Real yRe[N] "FFT coefficients";
discrete output Real yIm[N];
protected 
Integer N_d2(start = integer(floor(N/2)));
discrete Real fftMag[N] "Reconstructing mag";
discrete Real tmp[N_d2];
discrete Real fftArg[N] "Reconstructing phase";
public 
algorithm 
fftMag[:] := zeros(N);
tmp := zeros(N_d2);
tmp[1:size(mag, 1)] := mag.*1.4142135623730951*N/2;
fftMag[1:N_d2] := tmp[:];
fftMag[N-N_d2+2:1:end] := tmp[N_d2:-1:2];
tmp[:] := zeros(N_d2);
fftArg[:] := zeros(N);
tmp[1:size(arg, 1)] := arg[:].-1.5707963267948966;
fftArg[1:N_d2] := tmp[:];
fftArg[N-N_d2+2:1:end] := tmp[N_d2:-1:2];
yRe[1:N] := fftMag.*cos(fftArg);
yIm[1:N] := fftMag.*sin(fftArg);
end HPF.Utilities.fft_fromMagPhase;

  */
DYMOLA_STATIC struct HPF_Utilities_fftx_0fromMagPhase_struct HPF_Utilities_fftx_0fromMagPhase
  (RealArray   mag0_0, RealArray   arg0_0, int  N0_0) {
  PushContext("HPF.Utilities.fft_fromMagPhase")
  {
    /* Declare outputs and temporaries */
    RealArray    yRe0_0;
    RealArray    yIm0_0;
    int   Nx_0d2;
    RealArray    fftMag0_0;
    RealArray    tmp0_0;
    RealArray    fftArg0_0;
    MarkObject retmark_ = PushMark();
    yRe0_0=RealTemporary( 1, N0_0);
    RePushMark(&retmark_);
    RealFillAssign( yRe0_0, 0);
    yIm0_0=RealTemporary( 1, N0_0);
    RePushMark(&retmark_);
    RealFillAssign( yIm0_0, 0);
    Nx_0d2 = real2integer(floor(N0_0/(double)(2)));
    fftMag0_0=RealTemporary( 1, N0_0);
    PushMark();
    RealFillAssign( fftMag0_0, 0);
    tmp0_0=RealTemporary( 1, Nx_0d2);
    PushMark();
    RealFillAssign( tmp0_0, 0);
    fftArg0_0=RealTemporary( 1, N0_0);
    PushMark();
    RealFillAssign( fftArg0_0, 0);
    /* Start of real code */
      RealPutSub( RealConvertInteger (IntegerFill( 0, 1, (SizeType)(N0_0))), 
        fftMag0_0 ,Colon  , EndMark);
      Release();
      RealFillAssign (tmp0_0, 0);
      Release();
      RealPutSub( multScalar_For_1_0(mag0_0, 1.4142135623730951*N0_0/(double)(2)),
         tmp0_0 ,Range , (Integer)(1), (Integer)(DYNSizeSimple(mag0_0, 1))
         , EndMark);
      Release();
      RealPutSub( RealGetSub( tmp0_0 ,Colon  , EndMark), fftMag0_0 ,Range , 
        (Integer)(1), (Integer)(Nx_0d2) , EndMark);
      Release();
      RealPutSub( RealGetSub( tmp0_0 ,RangeRange , (Integer)(Nx_0d2), (Integer)(-1),
         (Integer)(2) , EndMark), fftMag0_0 ,RangeRange , (Integer)(N0_0-Nx_0d2+2),
         (Integer)(1), (Integer)(DYNSizeSimple(fftMag0_0, 1)) , EndMark);
      Release();
      RealPutSub( RealConvertInteger (IntegerFill( 0, 1, (SizeType)(Nx_0d2))), 
        tmp0_0 ,Colon  , EndMark);
      Release();
      RealPutSub( RealConvertInteger (IntegerFill( 0, 1, (SizeType)(N0_0))), 
        fftArg0_0 ,Colon  , EndMark);
      Release();
      RealPutSub( subScalar_For_1_0(RealGetSub( arg0_0 ,Colon  , EndMark), 
        1.5707963267948966), tmp0_0 ,Range , (Integer)(1), (Integer)(
        DYNSizeSimple(arg0_0, 1)) , EndMark);
      Release();
      RealPutSub( RealGetSub( tmp0_0 ,Colon  , EndMark), fftArg0_0 ,Range , 
        (Integer)(1), (Integer)(Nx_0d2) , EndMark);
      Release();
      RealPutSub( RealGetSub( tmp0_0 ,RangeRange , (Integer)(Nx_0d2), (Integer)(-1),
         (Integer)(2) , EndMark), fftArg0_0 ,RangeRange , (Integer)(N0_0-Nx_0d2+2),
         (Integer)(1), (Integer)(DYNSizeSimple(fftArg0_0, 1)) , EndMark);
      Release();
      RealPutSub( multScalar_For_1_0_1(fftMag0_0, cos_For_1_0(fftArg0_0)), 
        yRe0_0 ,Range , (Integer)(1), (Integer)(N0_0) , EndMark);
      Release();
      RealPutSub( multScalar_For_1_0_1(fftMag0_0, sin_For_1_0(fftArg0_0)), 
        yIm0_0 ,Range , (Integer)(1), (Integer)(N0_0) , EndMark);
      Release();
    /* Output section */
    PopMark(retmark_);
    PopContext()
    {
      struct HPF_Utilities_fftx_0fromMagPhase_struct out_;
      out_.yRe0_0_0member = yRe0_0;
      out_.yIm0_0_0member = yIm0_0;
      return out_;
    }
  }}

/* Flattened Modelica model:

function Modelica.Utilities.Streams.readRealMatrix
input String fileName "File where external data is stored" annotation (Dialog(loadSelector(filter="MATLAB MAT files (*.mat)", caption="Open MATLAB MAT file")));
input String matrixName "Name / identifier of the 2D Real array on the file";
input Integer nrow "Number of rows of the 2D Real array";
input Integer ncol "Number of columns of the 2D Real array";
input Boolean verboseRead(start = true) "= true: Print info message; = false: No info message";
discrete output Real matrix[nrow, ncol] "2D Real array";

external "C" ModelicaIO_readRealMatrix(fileName, matrixName, matrix, size(matrix, 1), size(matrix, 2), verboseRead);
annotation(Library={"ModelicaIO", "ModelicaMatIO", "zlib"}, LibraryDirectory="modelica://Modelica/Resources/Library");
end Modelica.Utilities.Streams.readRealMatrix;

  */
extern void (ModelicaIO_readRealMatrix)(const char* , const char* , double  *, 
  size_t, size_t, int );
DYMOLA_STATIC RealArray    Modelica_Utilities_Streams_readRealMatrix_M(
  const char*  fileName0_0, const char*  matrixName0_0, int  nrow0_0, int  
  ncol0_0, int  verboseRead0_0) {
  PushContext("Modelica.Utilities.Streams.readRealMatrix")
  {
    /* Declare outputs and temporaries */
    RealArray    matrix0_0;
    MarkObject retmark_ = PushMark();
    matrix0_0=RealTemporary( 2, nrow0_0, ncol0_0);
    RePushMark(&retmark_);
    RealFillAssign( matrix0_0, 0);
    /* Start of real code */
    {
      (ModelicaIO_readRealMatrix)(fileName0_0, matrixName0_0, matrix0_0.data, 
        matrix0_0.dims[1-1], matrix0_0.dims[2-1], verboseRead0_0);
      }
    /* Output section */
    PopMark(retmark_);
    PopContext()
    return matrix0_0;
  }}
DYMOLA_STATIC RealArray    cos_For_1_0(RealArray   u0_0) {
  PushContext("Vectorized ""cos")
   {
    RealArray  y0_0 = RealTemporary(  1, RealSize( u0_0, 1));
    int i_ ;
    int max_size_ = RealNrElements( y0_0);
    for(i_ = 0 ; i_ < max_size_; i_++) {
      y0_0.data[i_]=cos(u0_0.data[i_]);
    }
    PopContext()
    return y0_0;
  }
}
DYMOLA_STATIC RealArray    multScalar_For_1_0(RealArray   x_0x1, double  x_0x2)
   {
  PushContext("Vectorized ""multScalar")
   {
    RealArray  x_0y = RealTemporary(  1, RealSize( x_0x1, 1));
    int i_ ;
    int max_size_ = RealNrElements( x_0y);
    for(i_ = 0 ; i_ < max_size_; i_++) {
      x_0y.data[i_]=((x_0x1.data[i_])*(x_0x2));
    }
    PopContext()
    return x_0y;
  }
}
DYMOLA_STATIC RealArray    multScalar_For_1_0_1(RealArray   x_0x1, RealArray   
  x_0x2) {
  PushContext("Vectorized ""multScalar")
   {
    RealArray  x_0y = RealTemporary(  1, RealSize( x_0x1, 1));
    int i_ ;
    int max_size_ = RealNrElements( x_0y);
    for(i_ = 0 ; i_ < max_size_; i_++) {
      x_0y.data[i_]=((x_0x1.data[i_])*(x_0x2.data[i_]));
    }
    PopContext()
    return x_0y;
  }
}
DYMOLA_STATIC RealArray    sin_For_1_0(RealArray   u0_0) {
  PushContext("Vectorized ""sin")
   {
    RealArray  y0_0 = RealTemporary(  1, RealSize( u0_0, 1));
    int i_ ;
    int max_size_ = RealNrElements( y0_0);
    for(i_ = 0 ; i_ < max_size_; i_++) {
      y0_0.data[i_]=sin(u0_0.data[i_]);
    }
    PopContext()
    return y0_0;
  }
}
DYMOLA_STATIC RealArray    subScalar_For_1_0(RealArray   x_0x1, double  x_0x2) {
  PushContext("Vectorized ""subScalar")
   {
    RealArray  x_0y = RealTemporary(  1, RealSize( x_0x1, 1));
    int i_ ;
    int max_size_ = RealNrElements( x_0y);
    for(i_ = 0 ; i_ < max_size_; i_++) {
      x_0y.data[i_]=((x_0x1.data[i_])-(x_0x2));
    }
    PopContext()
    return x_0y;
  }
}
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    401
#define NP_    0
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   1
#define MAXAuxStrLen_   500
#define NHash1_ 877460455
#define NHash2_ 1292327870
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 2
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="HPF.Test.FFT_mag_phase_reconstruct";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
DYNSetAuxString(did_, "Z:/Documents/Research/DC Design Tool/Workspace/Modelica_HPF/HPF/Test/test_fft_mag_arg.mat",
   0);
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,3) = 32;
DYNX(W_,4) = 1;
DYNX(W_,0) = 60;
DYNX(W_,1) = 10000.0;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(DYNhelp,0) = divinvGuarded(DYNX(W_,0),"f");
DYNX(DYNhelp,1) = floor(DYNX(DYNhelp,0)*DYNX(W_,1));
DYNX(W_,2) = real2integer(DYNX(DYNhelp,1));
RealAssign (RealTemporaryDense( &DYNX(W_,5), 2, 32, 1), (PushModelContext(1,
  "Modelica.Utilities.Streams.readRealMatrix(resourceRetVal_fft, \"mag\", matDim_fft[1], 1, true)")
  Modelica_Utilities_Streams_readRealMatrix_M("Z:/Documents/Research/DC Design Tool/Workspace/Modelica_HPF/HPF/Test/test_fft_mag_arg.mat",
   "mag", (Integer)(DYNX(W_,3)), 1, true)));
PopAllMarks();
RealAssign (RealTemporaryDense( &DYNX(W_,37), 2, 32, 1), (PushModelContext(1,
  "Modelica.Utilities.Streams.readRealMatrix(resourceRetVal_fft, \"arg\", matDim_fft[1], 1, true)")
  Modelica_Utilities_Streams_readRealMatrix_M("Z:/Documents/Research/DC Design Tool/Workspace/Modelica_HPF/HPF/Test/test_fft_mag_arg.mat",
   "arg", (Integer)(DYNX(W_,3)), 1, true)));
PopAllMarks();
BoundParameterConstantSection
RealAssign (RealTemporaryDense( &DYNX(W_,69), 1, 166), RealTemporaryDense( 
  DymArrays0, 1, 166));
PopAllMarks();
RealAssign (RealTemporaryDense( &DYNX(W_,235), 1, 166), RealTemporaryDense( 
  DymArrays0, 1, 166));
PopAllMarks();
  {
    struct HPF_Utilities_fftx_0fromMagPhase_struct dummy_mult_=(PushModelContext(1,
      "HPF.Utilities.fft_fromMagPhase(dataFFT_mag[1:end, 1], dataFFT_arg[1:end, 1], 166)")
      HPF_Utilities_fftx_0fromMagPhase(RealGetSub( RealTemporaryDense( 
      &DYNX(W_,5), 2, 32, 1) ,Range , (Integer)(1), (Integer)(DYNSizeSimple(
      RealTemporaryDense( &DYNX(W_,5), 2, 32, 1), 1)) , Index, (Integer)(1)
       , EndMark), RealGetSub( RealTemporaryDense( &DYNX(W_,37), 2, 32, 1) ,
      Range , (Integer)(1), (Integer)(DYNSizeSimple(RealTemporaryDense( 
      &DYNX(W_,37), 2, 32, 1), 1)) , Index, (Integer)(1) , EndMark), 166));
    RealPutSub( dummy_mult_.yRe0_0_0member, RealTemporaryDense( &DYNX(W_,69), 1,
       166) ,Range , (Integer)(1), (Integer)(166) , EndMark);
    RealPutSub( dummy_mult_.yIm0_0_0member, RealTemporaryDense( &DYNX(W_,235), 1,
       166) ,Range , (Integer)(1), (Integer)(166) , EndMark);
  }
  PopAllMarks();
BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("f", "", 60, 0.0,0.0,0.0,0,513)
DeclareVariable("fs", "", 10000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("N", "[:#(type=Integer)]", 166, 0.0,0.0,0.0,0,517)
DeclareVariable("matDim_fft[1]", "[:#(type=Integer)]", 32, 0.0,0.0,0.0,0,517)
DeclareVariable("matDim_fft[2]", "[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,517)
DeclareVariable("dataFFT_mag[1, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[2, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[3, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[4, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[5, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[6, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[7, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[8, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[9, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[10, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[11, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[12, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[13, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[14, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[15, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[16, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[17, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[18, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[19, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[20, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[21, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[22, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[23, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[24, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[25, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[26, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[27, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[28, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[29, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[30, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[31, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_mag[32, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[1, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[2, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[3, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[4, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[5, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[6, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[7, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[8, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[9, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[10, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[11, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[12, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[13, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[14, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[15, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[16, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[17, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[18, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[19, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[20, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[21, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[22, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[23, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[24, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[25, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[26, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[27, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[28, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[29, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[30, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[31, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("dataFFT_arg[32, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[1]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[2]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[3]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[4]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[5]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[6]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[7]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[8]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[9]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[10]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[11]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[12]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[13]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[14]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[15]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[16]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[17]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[18]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[19]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[20]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[21]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[22]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[23]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[24]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[25]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[26]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[27]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[28]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[29]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[30]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[31]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[32]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[33]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[34]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[35]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[36]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[37]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[38]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[39]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[40]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[41]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[42]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[43]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[44]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[45]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[46]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[47]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[48]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[49]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[50]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[51]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[52]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[53]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[54]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[55]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[56]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[57]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[58]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[59]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[60]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[61]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[62]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[63]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[64]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[65]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[66]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[67]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[68]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[69]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[70]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[71]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[72]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[73]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[74]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[75]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[76]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[77]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[78]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[79]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[80]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[81]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[82]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[83]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[84]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[85]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[86]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[87]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[88]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[89]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[90]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[91]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[92]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[93]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[94]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[95]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[96]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[97]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[98]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[99]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[100]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[101]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[102]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[103]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[104]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[105]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[106]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[107]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[108]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[109]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[110]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[111]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[112]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[113]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[114]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[115]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[116]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[117]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[118]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[119]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[120]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[121]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[122]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[123]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[124]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[125]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[126]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[127]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[128]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[129]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[130]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[131]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[132]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[133]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[134]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[135]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[136]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[137]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[138]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[139]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[140]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[141]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[142]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[143]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[144]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[145]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[146]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[147]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[148]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[149]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[150]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[151]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[152]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[153]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[154]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[155]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[156]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[157]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[158]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[159]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[160]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[161]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[162]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[163]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[164]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[165]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yRe[166]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[1]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[2]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[3]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[4]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[5]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[6]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[7]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[8]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[9]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[10]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[11]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[12]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[13]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[14]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[15]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[16]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[17]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[18]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[19]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[20]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[21]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[22]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[23]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[24]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[25]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[26]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[27]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[28]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[29]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[30]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[31]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[32]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[33]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[34]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[35]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[36]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[37]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[38]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[39]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[40]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[41]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[42]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[43]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[44]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[45]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[46]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[47]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[48]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[49]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[50]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[51]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[52]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[53]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[54]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[55]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[56]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[57]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[58]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[59]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[60]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[61]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[62]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[63]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[64]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[65]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[66]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[67]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[68]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[69]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[70]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[71]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[72]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[73]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[74]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[75]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[76]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[77]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[78]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[79]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[80]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[81]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[82]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[83]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[84]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[85]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[86]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[87]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[88]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[89]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[90]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[91]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[92]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[93]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[94]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[95]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[96]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[97]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[98]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[99]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[100]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[101]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[102]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[103]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[104]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[105]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[106]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[107]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[108]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[109]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[110]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[111]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[112]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[113]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[114]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[115]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[116]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[117]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[118]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[119]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[120]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[121]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[122]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[123]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[124]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[125]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[126]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[127]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[128]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[129]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[130]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[131]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[132]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[133]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[134]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[135]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[136]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[137]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[138]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[139]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[140]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[141]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[142]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[143]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[144]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[145]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[146]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[147]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[148]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[149]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[150]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[151]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[152]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[153]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[154]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[155]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[156]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[157]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[158]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[159]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[160]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[161]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[162]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[163]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[164]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[165]", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("yIm[166]", "", 0, 0.0,0.0,0.0,0,513)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
EndDataBlock
