#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model flex_fmu_test
 Dymola Version 2020x (64-bit), 2019-10-10 translated this at Mon Apr  5 13:51:27 2021

  OutputCPUtime = true;
 */

#include <matrixop.h>
static double DymArrays0[1]={1.0};
static double DymArrays1[1]={2.0};
static double DymArrays2[1]={3.0};
static double DymArrays3[1]={4.0};
static double DymArrays4[1]={5.0};
static double DymArrays5[1]={6.0};
static double DymArrays6[1]={7.0};
static double DymArrays7[1]={8.0};
/* Declaration of C-structs */
struct DymStruc0;
struct DymStruc0 {
  int  id_0member;
};
DYMOLA_STATIC struct DymStruc0 DymStruc0_construct(int   id_02) {
  struct DymStruc0 dummy_0;
  dummy_0.id_0member = id_02;
  return dummy_0;
}
/* Prototypes for functions used in model */

#ifndef in5391302003259802818965_DoStep_C
#define in5391302003259802818965_DoStep_C 1
#include <stdlib.h>
#include "FMI/fmi2Import.h"
double in5391302003259802818965_fmiDoStep2(void*m, double currentTime, double stepSize) {
  struct dy_fmi2Extended*a=m;
  fmi2Status status=fmi2Fatal;
  fmi2Boolean value=fmi2False;
  if (a) {
    status=a->dyFmiDoStep(a->m, currentTime, stepSize, fmi2True);
    if(status==fmi2Discard){
      status = a->dyFmiGetBooleanStatus(a->m, fmi2Terminated, &value);
      if(value==fmi2True){
        terminate("Terminate signaled by the FMU");
      }
    }
  }
  if (status!=fmi2OK && status!=fmi2Warning) ModelicaError("DoStep failed");
  return 1.0;
}
#endif

#ifndef in5391302003259802818965_fmiEnterSlaveInitializationMode_C
#define in5391302003259802818965_fmiEnterSlaveInitializationMode_C 1
#include <stdlib.h>
#include "FMI/fmi2Import.h"
void in5391302003259802818965_fmiEnterSlaveInitializationMode2(void*m, double relativeTolerance, double tStart, int forceShutDownAtTStop, double tStop) {
  struct dy_fmi2Extended*a=m;
  fmi2Status status=fmi2Fatal;
  if (a) {
    if(a->currentMode==dyfmi2InstantiationMode){
      status=a->dyFmiSetupExperiment(a->m, fmi2True, relativeTolerance, tStart, forceShutDownAtTStop, tStop);
      status=a->dyFmiEnterInitializationMode(a->m);
      a->dyTriggered=0;
      a->dyLastTime=a->dyTime;
      a->currentMode=dyfmi2InitializationMode;
    }else{
      status=fmi2OK;
    }
  }
  if (status!=fmi2OK && status!=fmi2Warning) ModelicaError("InitializeSlave failed");
}
#endif

#ifndef in5391302003259802818965_fmiExitSlaveInitializationMode_C
#define in5391302003259802818965_fmiExitSlaveInitializationMode_C 1
#include <stdlib.h>
#include "FMI/fmi2Import.h"
void in5391302003259802818965_fmiExitSlaveInitializationMode2(void*m) {
  struct dy_fmi2Extended*a=m;
  fmi2Status status=fmi2Fatal;
  if (a) {
    status=a->dyFmiExitInitializationMode(a->m);
    a->dyTriggered=0;
    a->dyLastTime=a->dyTime;
    a->currentMode = dyfmi2EventMode;
  }
  if (status!=fmi2OK && status!=fmi2Warning) ModelicaError("fmiExitModelInitialization failed!");
  return;
}
#endif

#ifndef in5391302003259802818965_GetReal_C
#define in5391302003259802818965_GetReal_C 1
#include <stdlib.h>
#include "FMI/fmi2Import.h"
void in5391302003259802818965_fmiGetReal2(void*m, const int*refs, size_t nrefs, double*vals) {
  struct dy_fmi2Extended*a=m;
  fmi2Status status=fmi2Fatal;
  if (a) {
    status=a->dyFmiGetReal(a->m, refs, nrefs, vals);
  }
  if (status!=fmi2OK && status!=fmi2Warning) ModelicaError("GetReal failed");
}
#endif

#ifndef in5391302003259802818965_Instantiate_C
#define in5391302003259802818965_Instantiate_C 1
#include "FMI/fmi2Import.h"
#include <stdlib.h>
void in5391302003259802818965Logger(fmi2ComponentEnvironment componentEnvironment, fmi2String instanceName, fmi2Status status,
  fmi2String category, fmi2String message, ...) {
  char msg[4096];
  char buf[4096];
  va_list ap;
  int len;
  va_start(ap,message);
#if defined(_MSC_VER) && _MSC_VER>=1200
  len = _snprintf(msg, sizeof(msg)/sizeof(*msg), "%s: %s", instanceName, message);
  if (len < 0) goto fail;
  len = _vsnprintf(buf, sizeof(buf)/sizeof(*buf) - 2, msg, ap);
  if (len < 0) goto fail;
#else
  len = snprintf(msg, sizeof(msg)/sizeof(*msg), "%s: %s", instanceName, message);
  if (len < 0) goto fail;
  len = vsnprintf(buf, sizeof(buf)/sizeof(*buf) - 2, msg, ap);
  if (len < 0) goto fail;
#endif
  if( len>0 && len < 4096 && buf[len - 1]!='\n'){
    buf[len] = '\n';
    buf[len + 1] = 0;
  }
  va_end(ap);
  switch (status) {
    case fmi2Fatal:
      ModelicaMessage("[fmi2Fatal]: ");
      break;
    case fmi2Error:
      ModelicaMessage("[fmi2Error]: ");
      break;
    case fmi2Discard:
      ModelicaMessage("[fmi2Discard]: ");
      break;
    case fmi2Warning:
      ModelicaMessage("[fmi2Warning]: ");
      break;
    case fmi2OK:
      ModelicaMessage("[fmi2OK]: ");
      break;
  }
  ModelicaMessage(buf);
  return;
fail:
  ModelicaMessage("Logger failed, message too long?");
}
void * in5391302003259802818965_fmiInstantiateModel2(const char*instanceName, fmi2Boolean loggingOn, fmi2String resourceLocation) {
  static fmi2CallbackFunctions funcs = {&in5391302003259802818965Logger, &calloc, &free, NULL, NULL};
  struct dy_fmi2Extended* res;
  res = calloc(1, sizeof(struct dy_fmi2Extended));
  if (res!=0) {
    if (!(res->hInst=LoadLibrary("in.so"))) {
      ModelicaError("Loading of FMU dynamic link library (in.so) failed!");
      return 0;
    }
    if (!(res->dyFmiInstantiate=(fmi2InstantiateFunc)GetProcAddress(res->hInst,"fmi2Instantiate"))) {
      ModelicaError("GetProcAddress failed for fmi2Instantiate!");
      return 0;
    }
    if (!(res->dyFmiFreeInstance=(fmi2FreeInstanceFunc)GetProcAddress(res->hInst,"fmi2FreeInstance"))) {
      ModelicaError("GetProcAddress failed for fmi2FreeInstance!");
      return 0;
    }
    if (!(res->dyFmiSetupExperiment=(fmi2SetupExperimentFunc)GetProcAddress(res->hInst,"fmi2SetupExperiment"))) {
      ModelicaError("GetProcAddress failed for fmi2SetupExperiment!");
      return 0;
    }
    if (!(res->dyFmiEnterInitializationMode=(fmi2EnterInitializationModeFunc)GetProcAddress(res->hInst,"fmi2EnterInitializationMode"))) {
      ModelicaError("GetProcAddress failed for fmi2EnterInitializationMode!");
      return 0;
    }
    if (!(res->dyFmiExitInitializationMode=(fmi2ExitInitializationModeFunc)GetProcAddress(res->hInst,"fmi2ExitInitializationMode"))) {
      ModelicaError("GetProcAddress failed for fmi2ExitInitializationMode!");
      return 0;
    }
    if (!(res->dyFmiTerminate=(fmi2TerminateFunc)GetProcAddress(res->hInst,"fmi2Terminate"))) {
      ModelicaError("GetProcAddress failed for fmi2Terminate!");
      return 0;
    }
    if (!(res->dyFmiReset=(fmi2ResetFunc)GetProcAddress(res->hInst,"fmi2Reset"))) {
      ModelicaError("GetProcAddress failed for fmi2Reset!");
      return 0;
    }
    if (!(res->dyFmiSetReal=(fmi2SetRealFunc)GetProcAddress(res->hInst,"fmi2SetReal"))) {
      ModelicaError("GetProcAddress failed for fmi2SetReal!");
      return 0;
    }
    if (!(res->dyFmiGetReal=(fmi2GetRealFunc)GetProcAddress(res->hInst,"fmi2GetReal"))) {
      ModelicaError("GetProcAddress failed for fmi2GetReal!");
      return 0;
    }
    if (!(res->dyFmiSetInteger=(fmi2SetIntegerFunc)GetProcAddress(res->hInst,"fmi2SetInteger"))) {
      ModelicaError("GetProcAddress failed for fmi2SetInteger!");
      return 0;
    }
    if (!(res->dyFmiGetInteger=(fmi2GetIntegerFunc)GetProcAddress(res->hInst,"fmi2GetInteger"))) {
      ModelicaError("GetProcAddress failed for fmi2GetInteger!");
      return 0;
    }
    if (!(res->dyFmiSetBoolean=(fmi2SetBooleanFunc)GetProcAddress(res->hInst,"fmi2SetBoolean"))) {
      ModelicaError("GetProcAddress failed for fmi2SetBoolean!");
      return 0;
    }
    if (!(res->dyFmiGetBoolean=(fmi2GetBooleanFunc)GetProcAddress(res->hInst,"fmi2GetBoolean"))) {
      ModelicaError("GetProcAddress failed for fmi2GetBoolean!");
      return 0;
    }
    if (!(res->dyFmiSetDebugLogging=(fmi2SetDebugLoggingFunc)GetProcAddress(res->hInst,"fmi2SetDebugLogging"))) {
      ModelicaError("GetProcAddress failed for fmi2SetDebugLogging!");
      return 0;
    }
    if (!(res->dyFmiSetString=(fmi2SetStringFunc)GetProcAddress(res->hInst,"fmi2SetString"))) {
      ModelicaError("GetProcAddress failed for fmi2SetString!");
      return 0;
    }
    if (!(res->dyFmiGetString=(fmi2GetStringFunc)GetProcAddress(res->hInst,"fmi2GetString"))) {
      ModelicaError("GetProcAddress failed for fmi2GetString!");
      return 0;
    }
    if(!(res->dyFmiDoStep=(fmi2DoStepFunc)GetProcAddress(res->hInst,"fmi2DoStep"))){
      ModelicaError("GetProcAddress failed for fmi2DoStep!\n The model was imported as a Co-Simulation FMU but could not load the CS specific function fmiDoStep\n Verify that the FMU supports Co-Simulation");
      return 0;
    }
    if(!(res->dyFmiGetBooleanStatus=(fmi2GetBooleanStatusFunc)GetProcAddress(res->hInst,"fmi2GetBooleanStatus"))){
      ModelicaError("GetProcAddress failed for fmi2GetBooleanStatus!\n The model was imported as a Co-Simulation FMU but could not load the CS specific function fmiGetBooleanStatus\n Verify that the FMU supports Co-Simulation");
      return 0;
    }
    res->m=res->dyFmiInstantiate(instanceName, fmi2CoSimulation, "5391302f0032b59dd80281af8a9aee65",resourceLocation, &funcs, fmi2False, loggingOn);
    if (0==res->m) {free(res);res=0;ModelicaError("InstantiateModel failed");}
    else {res->dyTriggered=0;res->dyTime=res->dyLastTime=-1e37;res->discreteInputChanged=1;res->currentMode=dyfmi2InstantiationMode;res->dyLastStepTime=0;res->dyFMUstate=NULL;}
  }
  return res;
}
#endif

#ifndef in5391302003259802818965_Free_C
#define in5391302003259802818965_Free_C 1
#include "FMI/fmi2Import.h"
#include <stdlib.h>
void in5391302003259802818965_fmiFreeModelInstance2(void*m) {
  struct dy_fmi2Extended*a=m;
  if (a) {
    /*a->dyFmiSetDebugLogging(a->m,fmi2True,0,NULL);*/
    a->dyFmiTerminate(a->m);
    a->dyFmiFreeInstance(a->m);
    FreeLibrary(a->hInst);
    free(a);
  }
}
#endif

#ifndef in5391302003259802818965_SetReal_C
#define in5391302003259802818965_SetReal_C 1
#include <stdlib.h>
#include "FMI/fmi2Import.h"
void in5391302003259802818965_fmiSetReal2(void*m, const int*refs, size_t nrefs, const double*vals) {
  struct dy_fmi2Extended*a=m;
  fmi2Status status=fmi2Fatal;
  if(!nrefs){return;}
  if (a) {
    status=a->dyFmiSetReal(a->m, refs, nrefs, vals);
  }
  if (status!=fmi2OK && status!=fmi2Warning) ModelicaError("SetReal failed");
}
#endif
struct z_0gjgofpgggnhf_fmix_0Functions_fmiDoStep_M_struct {
  int   stepOK0_0_0member;
  double   postAvailable0_0_0member;
};
DYMOLA_STATIC struct z_0gjgofpgggnhf_fmix_0Functions_fmiDoStep_M_struct 
  z_0gjgofpgggnhf_fmix_0Functions_fmiDoStep_M(struct DymStruc0 fmi0_0, double  
  currentTime0_0, double  stepSize0_0, double  preAvailable0_0);
DYMOLA_STATIC double   z_0gjgofpgggnhf_fmix_0Functions_fmiEnterSlaveInitializationMode_M
  (struct DymStruc0 fmi0_0, double  relativeTolerance0_0, double  tStart0_0, int 
   forceShutDownAtTStop0_0, double  tStop0_0, double  preAvailable0_0);
DYMOLA_STATIC double   z_0gjgofpgggnhf_fmix_0Functions_fmiExitSlaveInitializationMode_M
  (struct DymStruc0 fmi0_0, double  preAvailable0_0);
DYMOLA_STATIC RealArray    z_0gjgofpgggnhf_fmix_0Functions_fmiGetReal_M(struct 
  DymStruc0 fmi0_0, IntegerArray   refs0_0);
DYMOLA_STATIC double   z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(struct 
  DymStruc0 fmi0_0, int  ref0_0);
DYMOLA_STATIC struct DymStruc0  z_0gjgofpgggnhf_fmix_0Functions_fmiModel_M(
  const char*  instanceName0_0, int  loggingOn0_0, const char*  resourceLocation0_0,
   int id_, int alwaysMakeNew_);
DYMOLA_STATIC void z_0gjgofpgggnhf_fmix_0Functions_fmiModel_destructor_M(void* 
  fmi0_0);
DYMOLA_STATIC void z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(struct DymStruc0
   fmi0_0, IntegerArray   refs0_0, RealArray   vals0_0);
/* Codes used in model */

/* Flattened Modelica model:

function 'in_fmu'.fmi_Functions.fmiDoStep
input 'in_fmu'.fmi_Functions.fmiModel fmi;
discrete input Real currentTime;
discrete input Real stepSize;
discrete input Real preAvailable;
output Boolean stepOK;
discrete output Real postAvailable(start = preAvailable);

external "C" stepOK = in5391302003259802818965_fmiDoStep2(fmi, currentTime, stepSize);
annotation(Include="
#ifndef in5391302003259802818965_DoStep_C
#define in5391302003259802818965_DoStep_C 1
#include <stdlib.h>
#include \"FMI/fmi2Import.h\"
double in5391302003259802818965_fmiDoStep2(void*m, double currentTime, double stepSize) {
  struct dy_fmi2Extended*a=m;
  fmi2Status status=fmi2Fatal;
  fmi2Boolean value=fmi2False;
  if (a) {
    status=a->dyFmiDoStep(a->m, currentTime, stepSize, fmi2True);
    if(status==fmi2Discard){
      status = a->dyFmiGetBooleanStatus(a->m, fmi2Terminated, &value);
      if(value==fmi2True){
        terminate(\"Terminate signaled by the FMU\");
      }
    }
  }
  if (status!=fmi2OK && status!=fmi2Warning) ModelicaError(\"DoStep failed\");
  return 1.0;
}
#endif", LibraryDirectory="modelica://'in_fmu'/Resources/Library/FMU/in/binaries");
end 'in_fmu'.fmi_Functions.fmiDoStep;

  */
DYMOLA_STATIC struct z_0gjgofpgggnhf_fmix_0Functions_fmiDoStep_M_struct 
  z_0gjgofpgggnhf_fmix_0Functions_fmiDoStep_M(struct DymStruc0 fmi0_0, double  
  currentTime0_0, double  stepSize0_0, double  preAvailable0_0) {
  PushContext("'in_fmu'.fmi_Functions.fmiDoStep")
  {
    /* Declare outputs and temporaries */
    int   stepOK0_0;
    double   postAvailable0_0;
    stepOK0_0=0;
    postAvailable0_0 = preAvailable0_0;
    /* Start of real code */
    {
      stepOK0_0 = (in5391302003259802818965_fmiDoStep2)(externalTable_[fmi0_0
        .id_0member].obj_, currentTime0_0, stepSize0_0);
      }
    /* Output section */
    PopContext()
    {
      struct z_0gjgofpgggnhf_fmix_0Functions_fmiDoStep_M_struct out_;
      out_.stepOK0_0_0member = stepOK0_0;
      out_.postAvailable0_0_0member = postAvailable0_0;
      return out_;
    }
  }}

/* Flattened Modelica model:

function 'in_fmu'.fmi_Functions.fmiEnterSlaveInitializationMode
input 'in_fmu'.fmi_Functions.fmiModel fmi;
discrete input Real relativeTolerance;
discrete input Real tStart;
input Boolean forceShutDownAtTStop;
discrete input Real tStop;
discrete input Real preAvailable;
discrete output Real postAvailable(start = preAvailable);

external "C" in5391302003259802818965_fmiEnterSlaveInitializationMode2(fmi, relativeTolerance, tStart, forceShutDownAtTStop, tStop);
annotation(Include="
#ifndef in5391302003259802818965_fmiEnterSlaveInitializationMode_C
#define in5391302003259802818965_fmiEnterSlaveInitializationMode_C 1
#include <stdlib.h>
#include \"FMI/fmi2Import.h\"
void in5391302003259802818965_fmiEnterSlaveInitializationMode2(void*m, double relativeTolerance, double tStart, int forceShutDownAtTStop, double tStop) {
  struct dy_fmi2Extended*a=m;
  fmi2Status status=fmi2Fatal;
  if (a) {
    if(a->currentMode==dyfmi2InstantiationMode){
      status=a->dyFmiSetupExperiment(a->m, fmi2True, relativeTolerance, tStart, forceShutDownAtTStop, tStop);
      status=a->dyFmiEnterInitializationMode(a->m);
      a->dyTriggered=0;
      a->dyLastTime=a->dyTime;
      a->currentMode=dyfmi2InitializationMode;
    }else{
      status=fmi2OK;
    }
  }
  if (status!=fmi2OK && status!=fmi2Warning) ModelicaError(\"InitializeSlave failed\");
}
#endif", LibraryDirectory="modelica://'in_fmu'/Resources/Library/FMU/in/binaries");
end 'in_fmu'.fmi_Functions.fmiEnterSlaveInitializationMode;

  */
DYMOLA_STATIC double   z_0gjgofpgggnhf_fmix_0Functions_fmiEnterSlaveInitializationMode_M
  (struct DymStruc0 fmi0_0, double  relativeTolerance0_0, double  tStart0_0, int 
   forceShutDownAtTStop0_0, double  tStop0_0, double  preAvailable0_0) {
  PushContext("'in_fmu'.fmi_Functions.fmiEnterSlaveInitializationMode")
  {
    /* Declare outputs and temporaries */
    double   postAvailable0_0;
    postAvailable0_0 = preAvailable0_0;
    /* Start of real code */
    {
      (in5391302003259802818965_fmiEnterSlaveInitializationMode2)(
        externalTable_[fmi0_0.id_0member].obj_, relativeTolerance0_0, tStart0_0,
         forceShutDownAtTStop0_0, tStop0_0);
      }
    /* Output section */
    PopContext()
    return postAvailable0_0;
  }}

/* Flattened Modelica model:

function 'in_fmu'.fmi_Functions.fmiExitSlaveInitializationMode
input 'in_fmu'.fmi_Functions.fmiModel fmi;
discrete input Real preAvailable;
discrete output Real postAvailable(start = preAvailable);

external "C" in5391302003259802818965_fmiExitSlaveInitializationMode2(fmi);
annotation(Include="
#ifndef in5391302003259802818965_fmiExitSlaveInitializationMode_C
#define in5391302003259802818965_fmiExitSlaveInitializationMode_C 1
#include <stdlib.h>
#include \"FMI/fmi2Import.h\"
void in5391302003259802818965_fmiExitSlaveInitializationMode2(void*m) {
  struct dy_fmi2Extended*a=m;
  fmi2Status status=fmi2Fatal;
  if (a) {
    status=a->dyFmiExitInitializationMode(a->m);
    a->dyTriggered=0;
    a->dyLastTime=a->dyTime;
    a->currentMode = dyfmi2EventMode;
  }
  if (status!=fmi2OK && status!=fmi2Warning) ModelicaError(\"fmiExitModelInitialization failed!\");
  return;
}
#endif", LibraryDirectory="modelica://'in_fmu'/Resources/Library/FMU/in/binaries");
end 'in_fmu'.fmi_Functions.fmiExitSlaveInitializationMode;

  */
DYMOLA_STATIC double   z_0gjgofpgggnhf_fmix_0Functions_fmiExitSlaveInitializationMode_M
  (struct DymStruc0 fmi0_0, double  preAvailable0_0) {
  PushContext("'in_fmu'.fmi_Functions.fmiExitSlaveInitializationMode")
  {
    /* Declare outputs and temporaries */
    double   postAvailable0_0;
    postAvailable0_0 = preAvailable0_0;
    /* Start of real code */
    {
      (in5391302003259802818965_fmiExitSlaveInitializationMode2)(externalTable_[
        fmi0_0.id_0member].obj_);
      }
    /* Output section */
    PopContext()
    return postAvailable0_0;
  }}

/* Flattened Modelica model:

function 'in_fmu'.fmi_Functions.fmiGetRealScalar
input 'in_fmu'.fmi_Functions.fmiModel fmi;
input Integer ref;
discrete output Real val;

algorithm 
val := scalar('in_fmu'.fmi_Functions.fmiGetReal(
fmi, 
{ref}));
end 'in_fmu'.fmi_Functions.fmiGetRealScalar;

  */
DYMOLA_STATIC double   z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(struct 
  DymStruc0 fmi0_0, int  ref0_0) {
  PushContext("'in_fmu'.fmi_Functions.fmiGetRealScalar")
  {
    /* Declare outputs and temporaries */
    double   val0_0;
    MarkObject retmark_ = PushMark();
    val0_0=0;
    /* Start of real code */
      val0_0 = Realscalar( z_0gjgofpgggnhf_fmix_0Functions_fmiGetReal_M(fmi0_0, 
        IntegerScalarArray ( 1, (int )(ref0_0))));
      Release();
    /* Output section */
    PopMark(retmark_);
    PopContext()
    return val0_0;
  }}

/* Flattened Modelica model:

function constructor
input String instanceName;
input Boolean loggingOn;
input String resourceLocation;
output 'in_fmu'.fmi_Functions.fmiModel fmi;

external "C" fmi = in5391302003259802818965_fmiInstantiateModel2(instanceName, loggingOn, resourceLocation);
annotation(Include="
#ifndef in5391302003259802818965_Instantiate_C
#define in5391302003259802818965_Instantiate_C 1
#include \"FMI/fmi2Import.h\"
#include <stdlib.h>
void in5391302003259802818965Logger(fmi2ComponentEnvironment componentEnvironment, fmi2String instanceName, fmi2Status status,
  fmi2String category, fmi2String message, ...) {
  char msg[4096];
  char buf[4096];
  va_list ap;
  int len;
  va_start(ap,message);
#if defined(_MSC_VER) && _MSC_VER>=1200
  len = _snprintf(msg, sizeof(msg)/sizeof(*msg), \"%s: %s\", instanceName, message);
  if (len < 0) goto fail;
  len = _vsnprintf(buf, sizeof(buf)/sizeof(*buf) - 2, msg, ap);
  if (len < 0) goto fail;
#else
  len = snprintf(msg, sizeof(msg)/sizeof(*msg), \"%s: %s\", instanceName, message);
  if (len < 0) goto fail;
  len = vsnprintf(buf, sizeof(buf)/sizeof(*buf) - 2, msg, ap);
  if (len < 0) goto fail;
#endif
  if( len>0 && len < 4096 && buf[len - 1]!='\\n'){
    buf[len] = '\\n';
    buf[len + 1] = 0;
  }
  va_end(ap);
  switch (status) {
    case fmi2Fatal:
      ModelicaMessage(\"[fmi2Fatal]: \");
      break;
    case fmi2Error:
      ModelicaMessage(\"[fmi2Error]: \");
      break;
    case fmi2Discard:
      ModelicaMessage(\"[fmi2Discard]: \");
      break;
    case fmi2Warning:
      ModelicaMessage(\"[fmi2Warning]: \");
      break;
    case fmi2OK:
      ModelicaMessage(\"[fmi2OK]: \");
      break;
  }
  ModelicaMessage(buf);
  return;
fail:
  ModelicaMessage(\"Logger failed, message too long?\");
}
void * in5391302003259802818965_fmiInstantiateModel2(const char*instanceName, fmi2Boolean loggingOn, fmi2String resourceLocation) {
  static fmi2CallbackFunctions funcs = {&in5391302003259802818965Logger, &calloc, &free, NULL, NULL};
  struct dy_fmi2Extended* res;
  res = calloc(1, sizeof(struct dy_fmi2Extended));
  if (res!=0) {
    if (!(res->hInst=LoadLibrary(\"in.so\"))) {
      ModelicaError(\"Loading of FMU dynamic link library (in.so) failed!\");
      return 0;
    }
    if (!(res->dyFmiInstantiate=(fmi2InstantiateFunc)GetProcAddress(res->hInst,\"fmi2Instantiate\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2Instantiate!\");
      return 0;
    }
    if (!(res->dyFmiFreeInstance=(fmi2FreeInstanceFunc)GetProcAddress(res->hInst,\"fmi2FreeInstance\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2FreeInstance!\");
      return 0;
    }
    if (!(res->dyFmiSetupExperiment=(fmi2SetupExperimentFunc)GetProcAddress(res->hInst,\"fmi2SetupExperiment\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2SetupExperiment!\");
      return 0;
    }
    if (!(res->dyFmiEnterInitializationMode=(fmi2EnterInitializationModeFunc)GetProcAddress(res->hInst,\"fmi2EnterInitializationMode\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2EnterInitializationMode!\");
      return 0;
    }
    if (!(res->dyFmiExitInitializationMode=(fmi2ExitInitializationModeFunc)GetProcAddress(res->hInst,\"fmi2ExitInitializationMode\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2ExitInitializationMode!\");
      return 0;
    }
    if (!(res->dyFmiTerminate=(fmi2TerminateFunc)GetProcAddress(res->hInst,\"fmi2Terminate\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2Terminate!\");
      return 0;
    }
    if (!(res->dyFmiReset=(fmi2ResetFunc)GetProcAddress(res->hInst,\"fmi2Reset\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2Reset!\");
      return 0;
    }
    if (!(res->dyFmiSetReal=(fmi2SetRealFunc)GetProcAddress(res->hInst,\"fmi2SetReal\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2SetReal!\");
      return 0;
    }
    if (!(res->dyFmiGetReal=(fmi2GetRealFunc)GetProcAddress(res->hInst,\"fmi2GetReal\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2GetReal!\");
      return 0;
    }
    if (!(res->dyFmiSetInteger=(fmi2SetIntegerFunc)GetProcAddress(res->hInst,\"fmi2SetInteger\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2SetInteger!\");
      return 0;
    }
    if (!(res->dyFmiGetInteger=(fmi2GetIntegerFunc)GetProcAddress(res->hInst,\"fmi2GetInteger\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2GetInteger!\");
      return 0;
    }
    if (!(res->dyFmiSetBoolean=(fmi2SetBooleanFunc)GetProcAddress(res->hInst,\"fmi2SetBoolean\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2SetBoolean!\");
      return 0;
    }
    if (!(res->dyFmiGetBoolean=(fmi2GetBooleanFunc)GetProcAddress(res->hInst,\"fmi2GetBoolean\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2GetBoolean!\");
      return 0;
    }
    if (!(res->dyFmiSetDebugLogging=(fmi2SetDebugLoggingFunc)GetProcAddress(res->hInst,\"fmi2SetDebugLogging\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2SetDebugLogging!\");
      return 0;
    }
    if (!(res->dyFmiSetString=(fmi2SetStringFunc)GetProcAddress(res->hInst,\"fmi2SetString\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2SetString!\");
      return 0;
    }
    if (!(res->dyFmiGetString=(fmi2GetStringFunc)GetProcAddress(res->hInst,\"fmi2GetString\"))) {
      ModelicaError(\"GetProcAddress failed for fmi2GetString!\");
      return 0;
    }
    if(!(res->dyFmiDoStep=(fmi2DoStepFunc)GetProcAddress(res->hInst,\"fmi2DoStep\"))){
      ModelicaError(\"GetProcAddress failed for fmi2DoStep!\\n The model was imported as a Co-Simulation FMU but could not load the CS specific function fmiDoStep\\n Verify that the FMU supports Co-Simulation\");
      return 0;
    }
    if(!(res->dyFmiGetBooleanStatus=(fmi2GetBooleanStatusFunc)GetProcAddress(res->hInst,\"fmi2GetBooleanStatus\"))){
      ModelicaError(\"GetProcAddress failed for fmi2GetBooleanStatus!\\n The model was imported as a Co-Simulation FMU but could not load the CS specific function fmiGetBooleanStatus\\n Verify that the FMU supports Co-Simulation\");
      return 0;
    }
    res->m=res->dyFmiInstantiate(instanceName, fmi2CoSimulation, \"5391302f0032b59dd80281af8a9aee65\",resourceLocation, &funcs, fmi2False, loggingOn);
    if (0==res->m) {free(res);res=0;ModelicaError(\"InstantiateModel failed\");}
    else {res->dyTriggered=0;res->dyTime=res->dyLastTime=-1e37;res->discreteInputChanged=1;res->currentMode=dyfmi2InstantiationMode;res->dyLastStepTime=0;res->dyFMUstate=NULL;}
  }
  return res;
}
#endif", LibraryDirectory="modelica://'in_fmu'/Resources/Library/FMU/in/binaries");
end constructor;

  */
DYMOLA_STATIC struct DymStruc0  z_0gjgofpgggnhf_fmix_0Functions_fmiModel_M(
  const char*  instanceName0_0, int  loggingOn0_0, const char*  resourceLocation0_0,
   int id_, int alwaysMakeNew_) {
  PushContext("'in_fmu'.fmi_Functions.fmiModel")
  {
    /* Declare outputs and temporaries */
    struct DymStruc0  fmi0_0;
    fmi0_0.id_0member=0;
    /* Start of real code */
    {
      fmi0_0.id_0member=id_;
      if (externalTable_[id_].destructor_ && externalTable_[id_].obj_ && alwaysMakeNew_) {
      void*x_=externalTable_[id_].obj_;
      externalTable_[id_].obj_=0;
      (*(externalTable_[id_].destructor_))(x_);
      } else if (!externalTable_[id_].destructor_) {externalTable_[id_].obj_=0;}
      #if (defined(_OPENMP) && !defined(DISABLE_DYMOLA_OPENMP))
      if (!(externalTable_[id_].haveLock_)) {omp_init_lock(&(externalTable_[id_].lockExternal_));externalTable_[id_].haveLock_=1;}
      #endif
      externalTable_[id_].destructor_=z_0gjgofpgggnhf_fmix_0Functions_fmiModel_destructor_M;

        if (!externalTable_[id_].obj_) externalTable_[id_].obj_ = (
        in5391302003259802818965_fmiInstantiateModel2)(instanceName0_0, 
        loggingOn0_0, resourceLocation0_0);
      }
    /* Output section */
    PopContext()
    return fmi0_0;
  }}

/* Flattened Modelica model:

function destructor
input 'in_fmu'.fmi_Functions.fmiModel fmi;

external "C" in5391302003259802818965_fmiFreeModelInstance2(fmi);
annotation(Include="
#ifndef in5391302003259802818965_Free_C
#define in5391302003259802818965_Free_C 1
#include \"FMI/fmi2Import.h\"
#include <stdlib.h>
void in5391302003259802818965_fmiFreeModelInstance2(void*m) {
  struct dy_fmi2Extended*a=m;
  if (a) {
    /*a->dyFmiSetDebugLogging(a->m,fmi2True,0,NULL);* /
    a->dyFmiTerminate(a->m);
    a->dyFmiFreeInstance(a->m);
    FreeLibrary(a->hInst);
    free(a);
  }
}
#endif", LibraryDirectory="modelica://'in_fmu'/Resources/Library/FMU/in/binaries");
end destructor;

  */
DYMOLA_STATIC void z_0gjgofpgggnhf_fmix_0Functions_fmiModel_destructor_M(void* 
  fmi0_0) {
  PushContext("'in_fmu'.fmi_Functions.fmiModel.destructor")
  {
    /* Declare outputs and temporaries */
    /* Start of real code */
    {
      (in5391302003259802818965_fmiFreeModelInstance2)(fmi0_0);
      }
    /* Output section */
    PopContext()
    return ;
  }}

/* Flattened Modelica model:

function 'in_fmu'.fmi_Functions.fmiSetReal
input 'in_fmu'.fmi_Functions.fmiModel fmi;
input Integer refs[:];
discrete input Real vals[size(refs, 1)];

external "C" in5391302003259802818965_fmiSetReal2(fmi, refs, size(refs, 1), vals);
annotation(Include="
#ifndef in5391302003259802818965_SetReal_C
#define in5391302003259802818965_SetReal_C 1
#include <stdlib.h>
#include \"FMI/fmi2Import.h\"
void in5391302003259802818965_fmiSetReal2(void*m, const int*refs, size_t nrefs, const double*vals) {
  struct dy_fmi2Extended*a=m;
  fmi2Status status=fmi2Fatal;
  if(!nrefs){return;}
  if (a) {
    status=a->dyFmiSetReal(a->m, refs, nrefs, vals);
  }
  if (status!=fmi2OK && status!=fmi2Warning) ModelicaError(\"SetReal failed\");
}
#endif", LibraryDirectory="modelica://'in_fmu'/Resources/Library/FMU/in/binaries");
end 'in_fmu'.fmi_Functions.fmiSetReal;

  */
DYMOLA_STATIC void z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(struct DymStruc0
   fmi0_0, IntegerArray   refs0_0, RealArray   vals0_0) {
  PushContext("'in_fmu'.fmi_Functions.fmiSetReal")
  AssertModelica(DYNSizeSimple(vals0_0,1)==DYNSizeSimple(refs0_0, 1),
    "size(vals, 1) == size(refs, 1)","Dimension check of input to function failed");
  {
    /* Declare outputs and temporaries */
    /* Start of real code */
    {
      (in5391302003259802818965_fmiSetReal2)(externalTable_[fmi0_0
        .id_0member].obj_, refs0_0.data, refs0_0.dims[1-1], vals0_0.data);
      }
    /* Output section */
    PopContext()
    return ;
  }}

/* Flattened Modelica model:

function 'in_fmu'.fmi_Functions.fmiGetReal
input 'in_fmu'.fmi_Functions.fmiModel fmi;
input Integer refs[:];
discrete output Real vals[size(refs, 1)];

external "C" in5391302003259802818965_fmiGetReal2(fmi, refs, size(refs, 1), vals);
annotation(Include="
#ifndef in5391302003259802818965_GetReal_C
#define in5391302003259802818965_GetReal_C 1
#include <stdlib.h>
#include \"FMI/fmi2Import.h\"
void in5391302003259802818965_fmiGetReal2(void*m, const int*refs, size_t nrefs, double*vals) {
  struct dy_fmi2Extended*a=m;
  fmi2Status status=fmi2Fatal;
  if (a) {
    status=a->dyFmiGetReal(a->m, refs, nrefs, vals);
  }
  if (status!=fmi2OK && status!=fmi2Warning) ModelicaError(\"GetReal failed\");
}
#endif", LibraryDirectory="modelica://'in_fmu'/Resources/Library/FMU/in/binaries");
end 'in_fmu'.fmi_Functions.fmiGetReal;

  */
DYMOLA_STATIC RealArray    z_0gjgofpgggnhf_fmix_0Functions_fmiGetReal_M(struct 
  DymStruc0 fmi0_0, IntegerArray   refs0_0) {
  PushContext("'in_fmu'.fmi_Functions.fmiGetReal")
  {
    /* Declare outputs and temporaries */
    RealArray    vals0_0;
    MarkObject retmark_ = PushMark();
    vals0_0=RealTemporary( 1, DYNSizeSimple(refs0_0, 1));
    RePushMark(&retmark_);
    RealFillAssign( vals0_0, 0);
    /* Start of real code */
    {
      (in5391302003259802818965_fmiGetReal2)(externalTable_[fmi0_0
        .id_0member].obj_, refs0_0.data, refs0_0.dims[1-1], vals0_0.data);
      }
    /* Output section */
    PopMark(retmark_);
    PopContext()
    return vals0_0;
  }}
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    0
#define NY_    2
#define NW_    48
#define NP_    24
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   2
#define MAXAuxStrLen_   500
#define NHash1_ -1550398233
#define NHash2_ -240314800
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  1
#define NSamp_ 1
#define NCons_ 0
#define NA_    8
#define SizePre_ 30
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 17
#define NrDymolaTimers_ 0
#define NWhen_ 4
#define NCheckIf_ 0
#define NGlobalHelp_ 1
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 1
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="flex_fmu_test";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={
#ifndef _LINUX64

#else
"/home/ubuntu/Resources/Library/FMU/in/binaries/linux64/in.so",
#endif
0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "/home/ubuntu/.dassaultsystemes/dymola/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations
DYNX(Y_,0) = CurrentClockTime;
if (DYNEvent) DYNX(Y_,1) += 1;

InitialSection
DYNSetAuxString(did_, "'in_fmu'", 0);
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,27) = false;
DYNX(W_,28) = true;
#endif
DYNSetAuxString(did_, "file:////home/ubuntu/Resources/Library/FMU/in/resources",
   1);
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(DYNhelp,0) = divinvGuarded(DYNX(DP_,11),"'in_fmu1'.fmi_NumberOfSteps");
DYNX(W_,29) = DYNX(DYNhelp,0)*(DYNX(DP_,10)-DYNX(DP_,9));
InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,31) = false;
DYNX(W_,32) = false;
#endif
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,1) = DYNX(DP_,0);
DYNX(W_,3) = DYNX(DP_,1);
DYNX(W_,5) = DYNX(DP_,2);
DYNX(W_,7) = DYNX(DP_,3);
DYNX(W_,9) = DYNX(DP_,4);
DYNX(W_,11) = DYNX(DP_,5);
DYNX(W_,13) = DYNX(DP_,6);
DYNX(W_,15) = DYNX(DP_,7);
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialBoundSection
DYNX(Aux_,0) = DYNX(W_,3);
DYNX(Aux_,1) = DYNX(W_,5);
DYNX(Aux_,2) = DYNX(W_,1);
DYNX(Aux_,3) = DYNX(W_,9);
DYNX(Aux_,4) = DYNX(W_,7);
DYNX(Aux_,5) = DYNX(W_,11);
DYNX(Aux_,7) = DYNX(W_,15);
DYNX(Aux_,6) = DYNX(W_,13);
DYNX(Aux_,8) = DYNX(W_,2);
DYNX(Aux_,9) = DYNX(W_,4);
DYNX(Aux_,10) = DYNX(W_,0);
DYNX(Aux_,11) = DYNX(W_,8);
DYNX(Aux_,12) = DYNX(W_,6);
DYNX(Aux_,13) = DYNX(W_,10);
DYNX(Aux_,14) = DYNX(W_,14);
DYNX(Aux_,15) = DYNX(W_,12);
DYNX(Aux_,16) = DYNX(W_,32);
InitialSection
InitialSection2
DYNX(W_,29) = divGuarded(DYNX(DP_,10)-DYNX(DP_,9),"'in_fmu1'.fmi_StopTime-'in_fmu1'.fmi_StartTime",
  DYNX(DP_,11),"'in_fmu1'.fmi_NumberOfSteps");
InitialBoundSection
{
  struct DymStruc0 dummy_DymStruc0;
  dummy_DymStruc0 = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiModel(\"'in_fmu'\", 'in_fmu1'.fmi_loggingOn, \"file:////home/ubuntu/Resources/Library/FMU/in/resources\", 0, 1)")
    z_0gjgofpgggnhf_fmix_0Functions_fmiModel_M("'in_fmu'", (Integer)(DYNX(DP_,8)),
     "file:////home/ubuntu/Resources/Library/FMU/in/resources", 0, 1));
  DYNX(W_,30) = dummy_DymStruc0.id_0member;
PopModelContext();
}
InitialSection2
  (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{1}, \n{'in_fmu1'._SchedulePlnmBLights_start})")
    z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct((Integer)(
    DYNX(W_,30))), IntegerTemporaryDense( DymArrays0, 1, 1), RealTemporaryDense( 
    &DYNX(DP_,0), 1, 1)));
  PopAllMarks();
  (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{2}, \n{'in_fmu1'._SchedulePlnmBDCHub_start})")
    z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct((Integer)(
    DYNX(W_,30))), IntegerTemporaryDense( DymArrays1, 1, 1), RealTemporaryDense( 
    &DYNX(DP_,1), 1, 1)));
  PopAllMarks();
  (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{3}, \n{'in_fmu1'._SchedulePlnmBFans_start})")
    z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct((Integer)(
    DYNX(W_,30))), IntegerTemporaryDense( DymArrays2, 1, 1), RealTemporaryDense( 
    &DYNX(DP_,2), 1, 1)));
  PopAllMarks();
  (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{4}, \n{'in_fmu1'._ScheduleZoneBLights_start})")
    z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct((Integer)(
    DYNX(W_,30))), IntegerTemporaryDense( DymArrays3, 1, 1), RealTemporaryDense( 
    &DYNX(DP_,3), 1, 1)));
  PopAllMarks();
  (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{5}, \n{'in_fmu1'._ScheduleZoneBFans_start})")
    z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct((Integer)(
    DYNX(W_,30))), IntegerTemporaryDense( DymArrays4, 1, 1), RealTemporaryDense( 
    &DYNX(DP_,4), 1, 1)));
  PopAllMarks();
  (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{6}, \n{'in_fmu1'._ScheduleZoneBMisc_start})")
    z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct((Integer)(
    DYNX(W_,30))), IntegerTemporaryDense( DymArrays5, 1, 1), RealTemporaryDense( 
    &DYNX(DP_,5), 1, 1)));
  PopAllMarks();
  (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{7}, \n{'in_fmu1'._ScheduleZoneBPlug_start})")
    z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct((Integer)(
    DYNX(W_,30))), IntegerTemporaryDense( DymArrays6, 1, 1), RealTemporaryDense( 
    &DYNX(DP_,6), 1, 1)));
  PopAllMarks();
  (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{8}, \n{'in_fmu1'._ScheduleZoneBPlugDC_start})")
    z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct((Integer)(
    DYNX(W_,30))), IntegerTemporaryDense( DymArrays7, 1, 1), RealTemporaryDense( 
    &DYNX(DP_,7), 1, 1)));
  PopAllMarks();
  (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiEnterSlaveInitializationMode(\n'in_fmu1'.fmi, \n'in_fmu1'.fmi_rTol, \n'in_fmu1'.fmi_StartTime, \n'in_fmu1'.fmi_forceShutDownAtStopTime, \n'in_fmu1'.fmi_StopTime, \n1)")
    z_0gjgofpgggnhf_fmix_0Functions_fmiEnterSlaveInitializationMode_M(
    DymStruc0_construct((Integer)(DYNX(W_,30))), DYNX(DP_,14), DYNX(DP_,9), 
    (Integer)(DYNX(DP_,13)), DYNX(DP_,10), 1));
  PopModelContext();
  DYNX(W_,33) = 1;
  DYNX(W_,34) = 1;
  DYNX(W_,36) = DYNTime;
DYNX(W_,1) = DYNX(DP_,16);
InitialBoundSection
DYNX(Aux_,2) = DYNX(W_,1);
InitialSection2
DYNX(W_,3) = DYNX(DP_,23);
InitialBoundSection
DYNX(Aux_,0) = DYNX(W_,3);
InitialSection2
DYNX(W_,5) = DYNX(DP_,17);
InitialBoundSection
DYNX(Aux_,1) = DYNX(W_,5);
InitialSection2
DYNX(W_,7) = DYNX(DP_,18);
InitialBoundSection
DYNX(Aux_,4) = DYNX(W_,7);
InitialSection2
DYNX(W_,9) = DYNX(DP_,19);
InitialBoundSection
DYNX(Aux_,3) = DYNX(W_,9);
InitialSection2
DYNX(W_,11) = DYNX(DP_,20);
InitialBoundSection
DYNX(Aux_,5) = DYNX(W_,11);
InitialSection2
DYNX(W_,13) = DYNX(DP_,21);
InitialBoundSection
DYNX(Aux_,6) = DYNX(W_,13);
InitialSection2
DYNX(W_,15) = DYNX(DP_,22);
InitialBoundSection
DYNX(Aux_,7) = DYNX(W_,15);
InitialSection2
DYNX(W_,31) = PRE(DYNX(W_,31), 0);
DYNX(W_,35) = PRE(DYNX(W_,35), 1);
DYNX(W_,32) = PRE(DYNX(W_,32), 2);
DYNX(W_,37) = PRE(DYNX(W_,37), 3);
DYNX(W_,38) = PRE(DYNX(W_,38), 4);
DYNX(W_,39) = PRE(DYNX(W_,39), 5);
DYNX(W_,40) = PRE(DYNX(W_,40), 6);
DYNX(W_,41) = PRE(DYNX(W_,41), 7);
DYNX(W_,42) = PRE(DYNX(W_,42), 8);
DYNX(W_,43) = PRE(DYNX(W_,43), 9);
DYNX(W_,44) = PRE(DYNX(W_,44), 10);
DYNX(W_,45) = PRE(DYNX(W_,45), 11);
DYNX(W_,46) = PRE(DYNX(W_,46), 12);
DYNX(W_,47) = PRE(DYNX(W_,47), 13);
  AssertModelica(DYNX(W_,29) > 0.0,"'in_fmu1'.fmi_CommunicationStepSize > 0.0", 
    "The parameter fmi_CommunicationStepSize has an invalid value, please set a positive value larger than 0.0");
  {
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{1}, \n{'in_fmu1'.SchedulePlnmBLights_.start})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays0, 1, 1), 
      RealTemporaryDense( &DYNX(Aux_,2), 1, 1)));
    PopAllMarks();
  }
  {
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{2}, \n{'in_fmu1'.SchedulePlnmBDCHub_.start})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays1, 1, 1), 
      RealTemporaryDense( &DYNX(Aux_,0), 1, 1)));
    PopAllMarks();
  }
  {
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{3}, \n{'in_fmu1'.SchedulePlnmBFans_.start})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays2, 1, 1), 
      RealTemporaryDense( &DYNX(Aux_,1), 1, 1)));
    PopAllMarks();
  }
  {
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{4}, \n{'in_fmu1'.ScheduleZoneBLights_.start})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays3, 1, 1), 
      RealTemporaryDense( &DYNX(Aux_,4), 1, 1)));
    PopAllMarks();
  }
  {
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{5}, \n{'in_fmu1'.ScheduleZoneBFans_.start})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays4, 1, 1), 
      RealTemporaryDense( &DYNX(Aux_,3), 1, 1)));
    PopAllMarks();
  }
  {
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{6}, \n{'in_fmu1'.ScheduleZoneBMisc_.start})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays5, 1, 1), 
      RealTemporaryDense( &DYNX(Aux_,5), 1, 1)));
    PopAllMarks();
  }
  {
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{7}, \n{'in_fmu1'.ScheduleZoneBPlug_.start})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays6, 1, 1), 
      RealTemporaryDense( &DYNX(Aux_,6), 1, 1)));
    PopAllMarks();
  }
  {
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{8}, \n{'in_fmu1'.ScheduleZoneBPlugDC_.start})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays7, 1, 1), 
      RealTemporaryDense( &DYNX(Aux_,7), 1, 1)));
    PopAllMarks();
  }
  if (DYNX(W_,33) >= 0 AND DYNX(W_,34) >= 0 AND  NOT DYNX(W_,31) AND  NOT 
    initial()) {
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiExitSlaveInitializationMode(\n'in_fmu1'.fmi, \n1)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiExitSlaveInitializationMode_M(
      DymStruc0_construct((Integer)(DYNX(W_,30))), 1));
    PopModelContext();
    DYNX(W_,31) = true;
  }
  if (GreaterEqualTime(DYNX(W_,29)+DYNX(DP_,9), 0)) {
    {
      int i_0_;
      int end_ = DYNX(DP_,12);
      int stepSizeIndex0_0_0;
      for(i_0_ = 0, stepSizeIndex0_0_0 = 1;stepSizeIndex0_0_0 <= end_;
        stepSizeIndex0_0_0 += 1 , ++i_0_) {
        DYNX(W_,35) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiDoStep(\n'in_fmu1'.fmi, \ntime+(stepSizeIndex-'in_fmu1'.stepSizeScaleFactor-1)*'in_fmu1'.fmi_CommunicationStepSize/'in_fmu1'.stepSizeScaleFactor, \n'in_fmu1'.fmi_CommunicationStepSize/'in_fmu1'.stepSizeScaleFactor, \n1)")
          z_0gjgofpgggnhf_fmix_0Functions_fmiDoStep_M(DymStruc0_construct(
          (Integer)(DYNX(W_,30))), DYNTime+divGuarded((stepSizeIndex0_0_0-
          DYNX(DP_,12)-1)*DYNX(W_,29),"(stepSizeIndex-'in_fmu1'.stepSizeScaleFactor-1)*'in_fmu1'.fmi_CommunicationStepSize",
          DYNX(DP_,12),"'in_fmu1'.stepSizeScaleFactor"), divGuarded(DYNX(W_,29),
          "'in_fmu1'.fmi_CommunicationStepSize",DYNX(DP_,12),"'in_fmu1'.stepSizeScaleFactor"),
           1).stepOK0_0_0member);
        PopModelContext();
      }
    }
    DYNX(W_,32) =  NOT DYNX(Aux_,16);
  }
  if ( NOT initial()) {
    DYNX(W_,37) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100001)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), 100001));
    PopModelContext();
    DYNX(W_,38) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100002)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), 100002));
    PopModelContext();
    DYNX(W_,39) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100003)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), 100003));
    PopModelContext();
    DYNX(W_,40) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100004)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), 100004));
    PopModelContext();
    DYNX(W_,41) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100005)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), 100005));
    PopModelContext();
    DYNX(W_,42) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100006)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), 100006));
    PopModelContext();
    DYNX(W_,43) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100007)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), 100007));
    PopModelContext();
    DYNX(W_,44) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100008)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), 100008));
    PopModelContext();
    DYNX(W_,45) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100009)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), 100009));
    PopModelContext();
    DYNX(W_,46) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100010)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), 100010));
    PopModelContext();
    DYNX(W_,47) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100011)")
      z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), 100011));
    PopModelContext();
  }
  DYNX(W_,16) = DYNX(W_,37);
  DYNX(W_,17) = DYNX(W_,38);
  DYNX(W_,18) = DYNX(W_,39);
  DYNX(W_,19) = DYNX(W_,40);
  DYNX(W_,20) = DYNX(W_,41);
  DYNX(W_,21) = DYNX(W_,42);
  DYNX(W_,22) = DYNX(W_,43);
  DYNX(W_,23) = DYNX(W_,44);
  DYNX(W_,24) = DYNX(W_,45);
  DYNX(W_,25) = DYNX(W_,46);
  DYNX(W_,26) = DYNX(W_,47);
DYNX(W_,14) = DYNX(Aux_,14);
DYNX(W_,12) = DYNX(Aux_,15);
DYNX(W_,10) = DYNX(Aux_,13);
DYNX(W_,8) = DYNX(Aux_,11);
DYNX(W_,6) = DYNX(Aux_,12);
DYNX(W_,4) = DYNX(Aux_,9);
DYNX(W_,2) = DYNX(Aux_,8);
DYNX(W_,0) = DYNX(Aux_,10);
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection

AcceptedSection1

AcceptedSection2
DYNX(W_,1) = DYNX(DP_,16);
DYNX(W_,3) = DYNX(DP_,23);
DYNX(W_,5) = DYNX(DP_,17);
DYNX(W_,7) = DYNX(DP_,18);
DYNX(W_,9) = DYNX(DP_,19);
DYNX(W_,11) = DYNX(DP_,20);
DYNX(W_,13) = DYNX(DP_,21);
DYNX(W_,15) = DYNX(DP_,22);
DYNX(W_,31) = PRE(DYNX(W_,31), 0);
DYNX(W_,35) = PRE(DYNX(W_,35), 1);
DYNX(W_,32) = PRE(DYNX(W_,32), 2);
DYNX(W_,37) = PRE(DYNX(W_,37), 3);
DYNX(W_,38) = PRE(DYNX(W_,38), 4);
DYNX(W_,39) = PRE(DYNX(W_,39), 5);
DYNX(W_,40) = PRE(DYNX(W_,40), 6);
DYNX(W_,41) = PRE(DYNX(W_,41), 7);
DYNX(W_,42) = PRE(DYNX(W_,42), 8);
DYNX(W_,43) = PRE(DYNX(W_,43), 9);
DYNX(W_,44) = PRE(DYNX(W_,44), 10);
DYNX(W_,45) = PRE(DYNX(W_,45), 11);
DYNX(W_,46) = PRE(DYNX(W_,46), 12);
DYNX(W_,47) = PRE(DYNX(W_,47), 13);
DYNX(W_,0) = PRE(DYNX(W_,0), 14);
DYNX(W_,2) = PRE(DYNX(W_,2), 15);
DYNX(W_,4) = PRE(DYNX(W_,4), 16);
DYNX(W_,6) = PRE(DYNX(W_,6), 17);
DYNX(W_,8) = PRE(DYNX(W_,8), 18);
DYNX(W_,10) = PRE(DYNX(W_,10), 19);
DYNX(W_,12) = PRE(DYNX(W_,12), 20);
DYNX(W_,14) = PRE(DYNX(W_,14), 21);
  AssertModelica(DYNX(W_,29) > 0.0,"'in_fmu1'.fmi_CommunicationStepSize > 0.0", 
    "The parameter fmi_CommunicationStepSize has an invalid value, please set a positive value larger than 0.0");
  beginwhenBlock
  vectorWhen(IntegerScalarArray ( 2, (int )(initial()), (int )(sampleNew(
    DYNX(DP_,9), DYNX(W_,29), 0))), 0, 2) 
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{1}, \n{pre('in_fmu1'.SchedulePlnmBLights)})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays0, 1, 1), 
      RealScalarArray ( 1, PRE(DYNX(W_,1), 22))));
    PopAllMarks();
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{2}, \n{pre('in_fmu1'.SchedulePlnmBDCHub)})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays1, 1, 1), 
      RealScalarArray ( 1, PRE(DYNX(W_,3), 23))));
    PopAllMarks();
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{3}, \n{pre('in_fmu1'.SchedulePlnmBFans)})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays2, 1, 1), 
      RealScalarArray ( 1, PRE(DYNX(W_,5), 24))));
    PopAllMarks();
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{4}, \n{pre('in_fmu1'.ScheduleZoneBLights)})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays3, 1, 1), 
      RealScalarArray ( 1, PRE(DYNX(W_,7), 25))));
    PopAllMarks();
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{5}, \n{pre('in_fmu1'.ScheduleZoneBFans)})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays4, 1, 1), 
      RealScalarArray ( 1, PRE(DYNX(W_,9), 26))));
    PopAllMarks();
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{6}, \n{pre('in_fmu1'.ScheduleZoneBMisc)})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays5, 1, 1), 
      RealScalarArray ( 1, PRE(DYNX(W_,11), 27))));
    PopAllMarks();
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{7}, \n{pre('in_fmu1'.ScheduleZoneBPlug)})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays6, 1, 1), 
      RealScalarArray ( 1, PRE(DYNX(W_,13), 28))));
    PopAllMarks();
    (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiSetReal(\n'in_fmu1'.fmi, \n{8}, \n{pre('in_fmu1'.ScheduleZoneBPlugDC)})")
      z_0gjgofpgggnhf_fmix_0Functions_fmiSetReal_M(DymStruc0_construct(
      (Integer)(DYNX(W_,30))), IntegerTemporaryDense( DymArrays7, 1, 1), 
      RealScalarArray ( 1, PRE(DYNX(W_,15), 29))));
    PopAllMarks();
    if (DYNX(W_,33) >= 0 AND DYNX(W_,34) >= 0 AND  NOT DYNX(W_,31) AND  NOT 
      initial()) {
      (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiExitSlaveInitializationMode(\n'in_fmu1'.fmi, \n1)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiExitSlaveInitializationMode_M(
        DymStruc0_construct((Integer)(DYNX(W_,30))), 1));
      PopModelContext();
      DYNX(W_,31) = true;
    }
    if (DYNTime >= DYNX(W_,29)+DYNX(DP_,9)) {
      {
        int end_ = DYNX(DP_,12);
        int stepSizeIndex0_0_0;
        for(stepSizeIndex0_0_0 = 1;stepSizeIndex0_0_0 <= end_;stepSizeIndex0_0_0
           += 1) {
          DYNX(W_,35) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiDoStep(\n'in_fmu1'.fmi, \ntime+(stepSizeIndex-'in_fmu1'.stepSizeScaleFactor-1)*'in_fmu1'.fmi_CommunicationStepSize/'in_fmu1'.stepSizeScaleFactor, \n'in_fmu1'.fmi_CommunicationStepSize/'in_fmu1'.stepSizeScaleFactor, \n1)")
            z_0gjgofpgggnhf_fmix_0Functions_fmiDoStep_M(DymStruc0_construct(
            (Integer)(DYNX(W_,30))), DYNTime+divGuarded((stepSizeIndex0_0_0-
            DYNX(DP_,12)-1)*DYNX(W_,29),"(stepSizeIndex-'in_fmu1'.stepSizeScaleFactor-1)*'in_fmu1'.fmi_CommunicationStepSize",
            DYNX(DP_,12),"'in_fmu1'.stepSizeScaleFactor"), divGuarded(
            DYNX(W_,29),"'in_fmu1'.fmi_CommunicationStepSize",DYNX(DP_,12),
            "'in_fmu1'.stepSizeScaleFactor"), 1).stepOK0_0_0member);
          PopModelContext();
        }
      }
      DYNX(W_,32) =  NOT PRE(DYNX(W_,32), 2);
    }
    if ( NOT initial()) {
      DYNX(W_,37) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100001)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
        (Integer)(DYNX(W_,30))), 100001));
      PopModelContext();
      DYNX(W_,38) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100002)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
        (Integer)(DYNX(W_,30))), 100002));
      PopModelContext();
      DYNX(W_,39) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100003)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
        (Integer)(DYNX(W_,30))), 100003));
      PopModelContext();
      DYNX(W_,40) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100004)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
        (Integer)(DYNX(W_,30))), 100004));
      PopModelContext();
      DYNX(W_,41) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100005)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
        (Integer)(DYNX(W_,30))), 100005));
      PopModelContext();
      DYNX(W_,42) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100006)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
        (Integer)(DYNX(W_,30))), 100006));
      PopModelContext();
      DYNX(W_,43) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100007)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
        (Integer)(DYNX(W_,30))), 100007));
      PopModelContext();
      DYNX(W_,44) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100008)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
        (Integer)(DYNX(W_,30))), 100008));
      PopModelContext();
      DYNX(W_,45) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100009)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
        (Integer)(DYNX(W_,30))), 100009));
      PopModelContext();
      DYNX(W_,46) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100010)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
        (Integer)(DYNX(W_,30))), 100010));
      PopModelContext();
      DYNX(W_,47) = (PushModelContext(1,"'in_fmu'.fmi_Functions.fmiGetRealScalar(\n'in_fmu1'.fmi, \n100011)")
        z_0gjgofpgggnhf_fmix_0Functions_fmiGetRealScalar(DymStruc0_construct(
        (Integer)(DYNX(W_,30))), 100011));
      PopModelContext();
    }
  endVectorWhen()
  endwhenBlock

  PopAllMarks();
  beginwhenBlock
  vectorWhen(IntegerScalarArray ( 2, (int )(PRE(DYNX(W_,32), 2)), (int )( NOT 
    PRE(DYNX(W_,32), 2))), 2, 2) 
    DYNX(W_,0) = PRE(DYNX(W_,1), 22);
    DYNX(W_,2) = PRE(DYNX(W_,3), 23);
    DYNX(W_,4) = PRE(DYNX(W_,5), 24);
    DYNX(W_,6) = PRE(DYNX(W_,7), 25);
    DYNX(W_,8) = PRE(DYNX(W_,9), 26);
    DYNX(W_,10) = PRE(DYNX(W_,11), 27);
    DYNX(W_,12) = PRE(DYNX(W_,13), 28);
    DYNX(W_,14) = PRE(DYNX(W_,15), 29);
  endVectorWhen()
  endwhenBlock

  PopAllMarks();
  DYNX(W_,16) = DYNX(W_,37);
  DYNX(W_,17) = DYNX(W_,38);
  DYNX(W_,18) = DYNX(W_,39);
  DYNX(W_,19) = DYNX(W_,40);
  DYNX(W_,20) = DYNX(W_,41);
  DYNX(W_,21) = DYNX(W_,42);
  DYNX(W_,22) = DYNX(W_,43);
  DYNX(W_,23) = DYNX(W_,44);
  DYNX(W_,24) = DYNX(W_,45);
  DYNX(W_,25) = DYNX(W_,46);
  DYNX(W_,26) = DYNX(W_,47);

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("'in_fmu1'._SchedulePlnmBLights_start", "", 0, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("'in_fmu1'._SchedulePlnmBLights_old", "", 0.0, 0.0,0.0,0.0,0,2704)
DeclareVariable("'in_fmu1'.SchedulePlnmBLights", "IDF line 1777", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareParameter("'in_fmu1'._SchedulePlnmBDCHub_start", "", 1, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("'in_fmu1'._SchedulePlnmBDCHub_old", "", 0.0, 0.0,0.0,0.0,0,2704)
DeclareVariable("'in_fmu1'.SchedulePlnmBDCHub", "IDF line 1813", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareParameter("'in_fmu1'._SchedulePlnmBFans_start", "", 2, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("'in_fmu1'._SchedulePlnmBFans_old", "", 0.0, 0.0,0.0,0.0,0,2704)
DeclareVariable("'in_fmu1'.SchedulePlnmBFans", "IDF line 1832", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareParameter("'in_fmu1'._ScheduleZoneBLights_start", "", 3, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("'in_fmu1'._ScheduleZoneBLights_old", "", 0.0, 0.0,0.0,0.0,0,2704)
DeclareVariable("'in_fmu1'.ScheduleZoneBLights", "IDF line 2657", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareParameter("'in_fmu1'._ScheduleZoneBFans_start", "", 4, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("'in_fmu1'._ScheduleZoneBFans_old", "", 0.0, 0.0,0.0,0.0,0,2704)
DeclareVariable("'in_fmu1'.ScheduleZoneBFans", "IDF line 2687", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareParameter("'in_fmu1'._ScheduleZoneBMisc_start", "", 5, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("'in_fmu1'._ScheduleZoneBMisc_old", "", 0.0, 0.0,0.0,0.0,0,2704)
DeclareVariable("'in_fmu1'.ScheduleZoneBMisc", "IDF line 2706", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareParameter("'in_fmu1'._ScheduleZoneBPlug_start", "", 6, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("'in_fmu1'._ScheduleZoneBPlug_old", "", 0.0, 0.0,0.0,0.0,0,2704)
DeclareVariable("'in_fmu1'.ScheduleZoneBPlug", "IDF line 2725", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareParameter("'in_fmu1'._ScheduleZoneBPlugDC_start", "", 7, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("'in_fmu1'._ScheduleZoneBPlugDC_old", "", 0.0, 0.0,0.0,0.0,0,2704)
DeclareVariable("'in_fmu1'.ScheduleZoneBPlugDC", "IDF line 2744", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("'in_fmu1'.PlnmB_zone_temp", "IDF line 6876", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("'in_fmu1'.ZoneB_zone_temp", "IDF line 6881", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("'in_fmu1'.site_outdoor_air_drybulb_temperature", \
"IDF line 6886", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("'in_fmu1'.PlnmB_electric_heating_rate", "IDF line 6891", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("'in_fmu1'.ZoneB_electric_heating_rate", "IDF line 6896", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("'in_fmu1'.PlnmB_lights_heating_rate", "IDF line 6901", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("'in_fmu1'.ZoneB_lights_heating_rate", "IDF line 6906", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("'in_fmu1'.PlnmB_cooling_setpoint", "IDF line 6911", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("'in_fmu1'.ZoneB_cooling_setpoint", "IDF line 6916", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("'in_fmu1'.cPlnmB_heating_setpoint", "IDF line 6921", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("'in_fmu1'.ZoneB_heating_setpoint", "IDF line 6926", 0.0, \
0.0,0.0,0.0,0,512)
DeclareParameter("'in_fmu1'.fmi_loggingOn", "[:#(type=Boolean)]", 8, false, \
0.0,0.0,0.0,0,562)
DeclareVariable("'in_fmu1'.fmi_InputTime", "Time point of input used when calling doStep. [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("'in_fmu1'.fmi_UsePreOnInputSignals", "[:#(type=Boolean)]", true,\
 0.0,0.0,0.0,0,515)
DeclareParameter("'in_fmu1'.fmi_StartTime", "", 9, 26265000, 0.0,0.0,0.0,0,560)
DeclareParameter("'in_fmu1'.fmi_StopTime", "", 10, 29029800, 0.0,0.0,0.0,0,560)
DeclareParameter("'in_fmu1'.fmi_NumberOfSteps", "", 11, 46080, 0.0,0.0,0.0,0,560)
DeclareVariable("'in_fmu1'.fmi_CommunicationStepSize", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("'in_fmu1'.stepSizeScaleFactor", "Number of doSteps called between two CommunicationStepSize [:#(type=Integer)]",\
 12, 1, 0.0,0.0,0.0,0,564)
DeclareParameter("'in_fmu1'.fmi_forceShutDownAtStopTime", "[:#(type=Boolean)]", 13,\
 false, 0.0,0.0,0.0,0,562)
DeclareParameter("'in_fmu1'.fmi_rTol", "relative tolerance for the internal solver of the fmu",\
 14, 1E-06, 0.0,0.0,0.0,0,560)
DeclareVariable("'in_fmu1'.fmi.id", "[:#(type=Integer)]", 0, 0.0,0.0,0.0,0,2565)
DeclareVariable("'in_fmu1'.fmi_exitInit", "[:#(type=Boolean)]", false, 0.0,0.0,\
0.0,0,2690)
DeclareVariable("'in_fmu1'.fmi_flip", "[:#(type=Boolean)]", false, 0.0,0.0,0.0,0,2706)
DeclareVariable("'in_fmu1'.fmi_rdum", "", 0, 0.0,0.0,0.0,0,2561)
DeclareVariable("'in_fmu1'.fmi_idum", "[:#(type=Integer)]", 0, 0.0,0.0,0.0,0,2565)
DeclareVariable("'in_fmu1'.fmi_StepOK", "[:#(type=Boolean)]", false, 0.0,0.0,0.0,\
0,2690)
DeclareParameter("'in_fmu1'.zeroOffset", "", 15, 0, 0.0,0.0,0.0,0,2608)
DeclareVariable("'in_fmu1'.myTimeStart", "[s]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("'in_fmu1'.PlnmB_zone_temp_internal", "", 0.0, 0.0,0.0,0.0,0,2688)
DeclareVariable("'in_fmu1'.ZoneB_zone_temp_internal", "", 0.0, 0.0,0.0,0.0,0,2688)
DeclareVariable("'in_fmu1'.site_outdoor_air_drybulb_temperature_internal", "", \
0.0, 0.0,0.0,0.0,0,2688)
DeclareVariable("'in_fmu1'.PlnmB_electric_heating_rate_internal", "", 0.0, \
0.0,0.0,0.0,0,2688)
DeclareVariable("'in_fmu1'.ZoneB_electric_heating_rate_internal", "", 0.0, \
0.0,0.0,0.0,0,2688)
DeclareVariable("'in_fmu1'.PlnmB_lights_heating_rate_internal", "", 0.0, \
0.0,0.0,0.0,0,2688)
DeclareVariable("'in_fmu1'.ZoneB_lights_heating_rate_internal", "", 0.0, \
0.0,0.0,0.0,0,2688)
DeclareVariable("'in_fmu1'.PlnmB_cooling_setpoint_internal", "", 0.0, 0.0,0.0,\
0.0,0,2688)
DeclareVariable("'in_fmu1'.ZoneB_cooling_setpoint_internal", "", 0.0, 0.0,0.0,\
0.0,0,2688)
DeclareVariable("'in_fmu1'.cPlnmB_heating_setpoint_internal", "", 0.0, 0.0,0.0,\
0.0,0,2688)
DeclareVariable("'in_fmu1'.ZoneB_heating_setpoint_internal", "", 0.0, 0.0,0.0,\
0.0,0,2688)
DeclareParameter("const.k", "Constant output value", 16, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("const.y", "Connector of Real output signal", "const.k", 1, 7, 16,\
 0)
DeclareParameter("const1.k", "Constant output value", 17, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("const1.y", "Connector of Real output signal", "const1.k", 1, 7, 17,\
 0)
DeclareParameter("const2.k", "Constant output value", 18, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("const2.y", "Connector of Real output signal", "const2.k", 1, 7, 18,\
 0)
DeclareParameter("const3.k", "Constant output value", 19, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("const3.y", "Connector of Real output signal", "const3.k", 1, 7, 19,\
 0)
DeclareParameter("const4.k", "Constant output value", 20, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("const4.y", "Connector of Real output signal", "const4.k", 1, 7, 20,\
 0)
DeclareParameter("const5.k", "Constant output value", 21, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("const5.y", "Connector of Real output signal", "const5.k", 1, 7, 21,\
 0)
DeclareParameter("const6.k", "Constant output value", 22, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("const6.y", "Connector of Real output signal", "const6.k", 1, 7, 22,\
 0)
DeclareParameter("const7.k", "Constant output value", 23, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("const7.y", "Connector of Real output signal", "const7.k", 1, 7, 23,\
 0)
DeclareOutput("CPUtime", "[s]", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("EventCounter", "", 1, 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartPreBlock
pre(DYNX(W_,44),"'in_fmu1'.PlnmB_cooling_setpoint_internal", 0.0, 10);
pre(DYNX(W_,40),"'in_fmu1'.PlnmB_electric_heating_rate_internal", 0.0, 6);
pre(DYNX(W_,42),"'in_fmu1'.PlnmB_lights_heating_rate_internal", 0.0, 8);
pre(DYNX(W_,37),"'in_fmu1'.PlnmB_zone_temp_internal", 0.0, 3);
preCont(DYNX(W_,3),"'in_fmu1'.SchedulePlnmBDCHub", DYNX(DP_,1), 23);
preCont(DYNX(W_,5),"'in_fmu1'.SchedulePlnmBFans", DYNX(DP_,2), 24);
preCont(DYNX(W_,1),"'in_fmu1'.SchedulePlnmBLights", DYNX(DP_,0), 22);
preCont(DYNX(W_,9),"'in_fmu1'.ScheduleZoneBFans", DYNX(DP_,4), 26);
preCont(DYNX(W_,7),"'in_fmu1'.ScheduleZoneBLights", DYNX(DP_,3), 25);
preCont(DYNX(W_,11),"'in_fmu1'.ScheduleZoneBMisc", DYNX(DP_,5), 27);
preCont(DYNX(W_,13),"'in_fmu1'.ScheduleZoneBPlug", DYNX(DP_,6), 28);
preCont(DYNX(W_,15),"'in_fmu1'.ScheduleZoneBPlugDC", DYNX(DP_,7), 29);
pre(DYNX(W_,45),"'in_fmu1'.ZoneB_cooling_setpoint_internal", 0.0, 11);
pre(DYNX(W_,41),"'in_fmu1'.ZoneB_electric_heating_rate_internal", 0.0, 7);
pre(DYNX(W_,47),"'in_fmu1'.ZoneB_heating_setpoint_internal", 0.0, 13);
pre(DYNX(W_,43),"'in_fmu1'.ZoneB_lights_heating_rate_internal", 0.0, 9);
pre(DYNX(W_,38),"'in_fmu1'.ZoneB_zone_temp_internal", 0.0, 4);
pre(DYNX(W_,2),"'in_fmu1'._SchedulePlnmBDCHub_old", 0.0, 15);
pre(DYNX(W_,4),"'in_fmu1'._SchedulePlnmBFans_old", 0.0, 16);
pre(DYNX(W_,0),"'in_fmu1'._SchedulePlnmBLights_old", 0.0, 14);
pre(DYNX(W_,8),"'in_fmu1'._ScheduleZoneBFans_old", 0.0, 18);
pre(DYNX(W_,6),"'in_fmu1'._ScheduleZoneBLights_old", 0.0, 17);
pre(DYNX(W_,10),"'in_fmu1'._ScheduleZoneBMisc_old", 0.0, 19);
pre(DYNX(W_,14),"'in_fmu1'._ScheduleZoneBPlugDC_old", 0.0, 21);
pre(DYNX(W_,12),"'in_fmu1'._ScheduleZoneBPlug_old", 0.0, 20);
pre(DYNX(W_,46),"'in_fmu1'.cPlnmB_heating_setpoint_internal", 0.0, 12);
pre(DYNX(W_,35),"'in_fmu1'.fmi_StepOK", false, 1);
pre(DYNX(W_,31),"'in_fmu1'.fmi_exitInit", false, 0);
pre(DYNX(W_,32),"'in_fmu1'.fmi_flip", false, 2);
pre(DYNX(W_,39),"'in_fmu1'.site_outdoor_air_drybulb_temperature_internal", 0.0, 5);
EndPreBlock
UpdateQEvaluate(4)
UpdateSampleCounters(1)
EndDataBlock
