%% Phasor Model - Timings
% Run each of the four phasor models multiple times, clearing the workspace
% in between, and report timings.
%
% Before running this script, go into Phase_Model_*.m and set the
% 'skip_reports' option to true, to ensure accurate timings.

%% Setup
% Number of repititions
reps = 20;

% Timings
timings = struct();
timings.AC1 = zeros(reps,1);
timings.AC2 = zeros(reps,1);
timings.AC3 = zeros(reps,1);
timings.DC  = zeros(reps,1);

%% Run Models
% Iterate on timings
for kk = 1:reps
    % AC1
    clearvars -except kk timings reps
    tic
    Phasor_Model_AC1
    timings.AC1(kk) = toc;
    
    % AC2
    clearvars -except kk timings reps
    tic
    Phasor_Model_AC2
    timings.AC2(kk) = toc;
    
    % AC3
    clearvars -except kk timings reps
    tic
    Phasor_Model_AC3
    timings.AC3(kk) = toc;
    
    % AC4
    clearvars -except kk timings reps
    tic
    Phasor_Model_DC
    timings.DC(kk) = toc;
end

% Clean up
clearvars -except timings reps

%% Reporting
% Evaluation timing results (min, median, max, avg)
timing_matrix = [ ...
    min(timings.AC1), median(timings.AC1), max(timings.AC1), mean(timings.AC1); ...
    min(timings.AC2), median(timings.AC2), max(timings.AC2), mean(timings.AC2); ...
    min(timings.AC3), median(timings.AC3), max(timings.AC3), mean(timings.AC3); ...
    min(timings.DC),  median(timings.DC),  max(timings.DC),  mean(timings.DC)  ...
];

% If this were MATLAB 2013b or newer, I could use table() here. But, alas,
% I am on 2013a.

% Display as UI table
uitable( ...
    'Data', timing_matrix, ...
    'ColumnName', {'Min', 'Median', 'Max', 'Average'}, ...
    'RowName', {'AC1', 'AC2', 'AC3', 'DC'} ...
);

% Timings cell matrix
timing_cells = { ...
    'Scenario', 'Min', 'Median', 'Max', 'Average';
    'AC1', ...
        min(timings.AC1), ...
        median(timings.AC1), ...
        max(timings.AC1), ...
        mean(timings.AC1); ...
    'AC2', ...
        min(timings.AC2), ...
        median(timings.AC2), ...
        max(timings.AC2), ...
        mean(timings.AC2); ...
    'AC3', ...
        min(timings.AC3), ...
        median(timings.AC3), ...
        max(timings.AC3), ...
        mean(timings.AC3); ...
    'DC', ...
        min(timings.DC), ...
        median(timings.DC), ...
        max(timings.DC), ...
        mean(timings.DC); ...
};

% Write Excel
xlswrite('HPF Timings.xlsx', timing_cells);

